//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elsheimy.Components.Linears.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elsheimy.Components.Linears.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-dimensional required..
        /// </summary>
        internal static string Exception_2DRequired {
            get {
                return ResourceManager.GetString("Exception_2DRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-dimensional required..
        /// </summary>
        internal static string Exception_3DRequired {
            get {
                return ResourceManager.GetString("Exception_3DRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column count mismatch..
        /// </summary>
        internal static string Exception_ColumnCountMismatch {
            get {
                return ResourceManager.GetString("Exception_ColumnCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions mismatch..
        /// </summary>
        internal static string Exception_DimensionsMismatch {
            get {
                return ResourceManager.GetString("Exception_DimensionsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid axis..
        /// </summary>
        internal static string Exception_InvalidAxis {
            get {
                return ResourceManager.GetString("Exception_InvalidAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid matrix..
        /// </summary>
        internal static string Exception_InvalidMatrix {
            get {
                return ResourceManager.GetString("Exception_InvalidMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrices dimensions mismatch..
        /// </summary>
        internal static string Exception_MatricesDimensionsMismatch {
            get {
                return ResourceManager.GetString("Exception_MatricesDimensionsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Middle&apos; is not supported..
        /// </summary>
        internal static string Exception_MiddleNotSupported {
            get {
                return ResourceManager.GetString("Exception_MiddleNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No augmented columns found..
        /// </summary>
        internal static string Exception_NoAugmentedColumns {
            get {
                return ResourceManager.GetString("Exception_NoAugmentedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square matrix required..
        /// </summary>
        internal static string Exception_RequiredSquareMatrix {
            get {
                return ResourceManager.GetString("Exception_RequiredSquareMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row count mismatch..
        /// </summary>
        internal static string Exception_RowCountMismatch {
            get {
                return ResourceManager.GetString("Exception_RowCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmented columns must be less than total columns..
        /// </summary>
        internal static string Exception_TooMuchAugmentedColumns {
            get {
                return ResourceManager.GetString("Exception_TooMuchAugmentedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much columns to remove..
        /// </summary>
        internal static string Exception_TooMuchColumnsRemove {
            get {
                return ResourceManager.GetString("Exception_TooMuchColumnsRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much rows to remove..
        /// </summary>
        internal static string Exception_TooMuchRowsRemove {
            get {
                return ResourceManager.GetString("Exception_TooMuchRowsRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined product. n columns of first matrix must equal to n rows of second matrix..
        /// </summary>
        internal static string Exception_UndefinedProduct {
            get {
                return ResourceManager.GetString("Exception_UndefinedProduct", resourceCulture);
            }
        }
    }
}
